database:
  database: skyportal_test
  user: skyportal
  host: localhost
  port: 5432
  password:

server:
  auth:
    debug_login: True
    google_oauth2_key:
    google_oauth2_secret:

misc:
  photometry_detection_threshold_nsigma: 3.0

twilio:
  # Twilio Sendgrid API configs
  # This needs to be set to a valid, Sendgrid-registered address in config.yaml
  from_email:
  # This needs to be obtained via Sendgrid setup on their site
  sendgrid_api_key:

  # Twilio SMS API configs
  # These values must be valid ones from the Twitter API console
  from_number:
  sms_account_sid:
  sms_auth_token:

invitations:
  enabled: False
  days_until_expiry: 3
  email_subject: "You've been invited to collaborate on SkyPortal"
  email_body_preamble: | # This can include HTML tags
    Welcome to <b>SkyPortal</b>!
    <br />
    Some other text here.

notifications:
  enabled: True

testing: true

services:
  paths:
    - ./baselayer/services
    - ./skyportal/services

test_server:
  port: 64502
  # Reset the cache every * days
  refresh_cache_days: 7
  redirects:
    # List of routes listened for by the test server, and the real URLs that
    # requests should be redirected to. Requests will be forwarded by the
    # test server, cached, and responses played back to the API as if it came
    # from the real server.
    /node_agent2/node_agent: http://161.72.57.3:8080 # LT
    /api/requestgroups/: https://observe.lco.global # LCO

app:
  lt_host: localhost
  lt_port: 64502
  lco_protocol: http
  lco_host: localhost
  lco_port: 64502
